Require lazy_static 1.1
Without this a `cargo build -Z minimal-versions` fails with:
```
error: cannot find macro `__lazy_static_internal` in this scope
  --> src/canvas.rs:21:1
   |
21 | / lazy_static! {
22 | |     static ref BITMAP_1BPP_TO_8BPP_LUT: [[u8; 8]; 256] = {
23 | |         let mut lut = [[0; 8]; 256];
24 | |         for byte in 0..0x100 {
...  |
34 | |     };
35 | | }
   | |_^
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0425]: cannot find value `BITMAP_1BPP_TO_8BPP_LUT` in this scope
```